### ISSUE TITLE
Ionic Push GCM_INVALID_AUTH

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud-angular#14]
Hey guys!

I'm setting up Push notifications for my app and am using the _sweet_ [new docs](http://docs.ionic.io/services/push/) yall created (seriously, these are great!).  Unfortunately, I've hit a snag... While the notification creates successfully (with a status of 'enqueue'), upon checking the /messages endpoint I discover that it failed to send because of a GCM_INVALID_AUTH error.  In looking at the API docs (also awesome), it suggests that either my API key or GCM project id are incorrect.  However, I've double and triple checked this and have found them both to be correct in all places...

The only difference that I could find, is that when creating the API key in the Google Dev Console, their process has changed such that you can no longer specify a type of credential (ie: Browser API key, as is suggested in the docs).  Instead, it just creates a generic Api key, where you can specify platform restrictions (ie: Browser, server, android/ios app).  

So I guess my question is, could this be the problem?  Or are you guys aware of anything that could be going on here with GCM/ionic.io?

Thanks for your time!

For reference, this is my cloud settings:

```
const cloudSettings: CloudSettings = {
    'core': {
        'app_id': '<my app id>'
    },
    'push': {
        'sender_id': '<my GCM Project Id>'
    }
};
```

Here is my ionic push plugin statement in the config.xml:

```
  <plugin name="phonegap-plugin-push" spec="~1.8.1">
    <variable name="SENDER_ID" value="<my GCM Project Id>"/>
  </plugin>
```

My Security profile in ionic.io is configured to use the GCM Api key as created through the Google Dev Dashboard...

**Comment by joshgarwood** [comment]
@Fuiste @dwieeb  Sounds like Google pulled a switcheroo on us (grrr!)... According to these guys, they had to create a firebase project to get this to work... Can y'all confirm that this is the appropriate fix?

https://forum.ionicframework.com/t/ionic-push-notification-for-android-keeps-giving-me-error-gcm-invalid-auth/63041/3

**Comment by ericb** [comment]
The API key should work regardless of the 'browser api' setting they used to have. I had recently setup a project that used the same setup. Are you sure you've updated the API key in the correct security profile? 

As far as FCM goes, I believe you can use an FCM project directly in replacement of GCM (though I've only heard reports of this, I have not yet tested directly). However, we have still been creating GCM projects per our documentation and everything appears to be in working order.

Is it possible that the project and API key were created but not yet enabled?

**Comment by joshgarwood** [comment]
Hey @ericb yes, I would have thought the same for sure (that the API key should work regardless of GCM or FCM), but given my repeated attempts to get it to work (and double checking the the Api keys are correct, that the project is enabled, and the my security profiles or properly configured)... I'm left feeling skeptical.  Especially since multiple other people have been [experiencing the same issue](https://forum.ionicframework.com/t/ionic-push-notification-for-android-keeps-giving-me-error-gcm-invalid-auth/63041/2), I'm going to give FCM a try to see if I have any luck there.  

I'll report back with the status.

Thanks!

**Comment by joshgarwood** [comment]
@ericb I can confirm that using FCM does in fact work (it actually creates a new project visible in the GCM portal with the correct key type), whereas my newly created GCM project did not.  Perhaps it's a coincidence, but this is consistent with what other people have reported on the Ionic forums.

**Comment by Fuiste** [comment]
Hey @joshgarwood, just a quick heads up that I've duplicated this on our end and it does in fact look like Google pulled a past one with GCM's functionality.

I'm working on a new version of the docs to go out ASAP, thanks for the heads up there.

**Comment by Fuiste** [comment]
Whoops, forgot to close this issue when I updated the docs.  Everything should be patched up on that front now.
