### ISSUE TITLE
Cannot resolve symbol 'PushToken

### ISSUE THREAD

**Issue by amymarsh4work** [driftyco/ionic-cloud-angular#15]
Hi,
I'm attempting to setup push in my app.ts and following the 'Injecting Push' section in the documentation here: http://docs.ionic.io/services/push/#injecting-push

Problem I'm facing is in my import statement:
import {Deploy, CloudSettings, provideCloud, Push, **PushToken**} from '@ionic/cloud-angular';
The PushToken doesn't come up in autocomplete, shows up in red, and has an error "Cannot resolve symbol 'PushToken'".

I just updated ionic-cloud-angular to version 0.4.0 - that didn't help.

Here's my ionic info:
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175 

Please help :)
Thanks,
Amy

**Comment by imhoffd** [comment]
@amymarsh4work ~~Just a docs update! You no longer need to import PushToken. Thanks for the issue, I'll fix up the docs.~~

Sorry, was confused briefly. Looking into this.

**Comment by imhoffd** [comment]
Hmm, I'm not seeing this behavior. Can you confirm you have 0.9.0 of the cloud client? 

`npm ls --depth=0 | grep cloud`

**Comment by amymarsh4work** [comment]
The command returned:
+-- @ionic/cloud-angular@0.4.0

However, after I updated earlier today, I was seeing this:
`-- @ionic/cloud-angular@0.4.0 
`-- @ionic/cloud@0.9.0

**Comment by amymarsh4work** [comment]
Hey! I opened the project today and it's fine. I think Webstorm just needed to do whatever it needs to. Looks like updating fixed it but I needed to be patient.

**Comment by imhoffd** [comment]
Cool! Yeah I didn't notice anything wrong with a fresh install, so glad to know things are working! 👍

**Comment by rajshkr** [comment]
@dwieeb I am facing this problem

[13:29:51]  typescript compiler ready in 7.39 s
[13:29:51]  bundle dev started ...
[13:29:55]  Error: Could not resolve '@ionic/cloud-angular' from /Users/***/***/repos/clientapp/.tmp/app/app.module.js
    at Error (native)

output of npm ls --depth=0 | grep cloud

├── @ionic/cloud-angular@0.8.0

ionic info

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.4.0
Xcode version: Not installed
