### ISSUE TITLE
cloud.js : no such file or directory

### ISSUE THREAD

**Issue by graphicsxp** [driftyco/ionic-cloud-angular#17]
I can't figure out why I'm getting this error when running `ionic serve` after using the package.

Why is it looking for a cloud.js file that does not exist ?

```
[16:35:43] Error on fetch for @ionic/cloud.js at file:///c:/ionic/orderForms/nod
e_modules/@ionic/cloud.js
        Loading @ionic/cloud-angular
        Loading app/dist/app.js
        Error: ENOENT: no such file or directory, open 'c:\ionic\orderForms\node
_modules\@ionic\cloud.js'
    at Error (native)
```

**Comment by graphicsxp** [comment]
I realized that there is a dependency on ionic-cloud, which was not installed. 

I've installed it, but I'm still getting the same error.

**Comment by imhoffd** [comment]
Ionic 1/2?
NPM version?
What is `app/dist`?

The error looks very weird to me. Nothing in our code refers to a `cloud.js`. Also, `@ionic/cloud` is installed when `@ionic/cloud-angular` is installed through NPM.

**Comment by graphicsxp** [comment]
ionic 2
npm, I don't know I will check tomorrow at work
app/dist is the destination folder where all files are moved by a gulp script when running ionic serve.

well in my case @ionic/cloud was NOT installed with @ionic/cloud. I had to installed it manually.

Indeed, there is no cloud.js file, I don't get it.

Also I'm using systemJS, not sure if this could be the problem....

**Comment by imhoffd** [comment]
In npm 3 they changed dependency resolution strategies: https://docs.npmjs.com/how-npm-works/npm3

My guess is @ionic/cloud was installed, but it put the code in `@ionic/cloud-angular/node_modules/@ionic/cloud`, because you may be using npm 2.

**Comment by graphicsxp** [comment]
ok, I will check it out tomorrow morning and will let you know. thanks !

2016-09-14 20:06 GMT+02:00 Daniel Imhoff notifications@github.com:
