### ISSUE TITLE
Implement Ionic cloud (JavaScript)

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic-cloud-angular#18]
I wanted to implement the below code in JS as my Ionic2 is written in JS, I was not able to implement the below in JS as I received `Unexpected token`

```
    const cloudSettings: CloudSettings = {
    'core': {
    'app_id': 'YOUR-APP-ID'
     }
     };
```

**Comment by devnetics** [comment]
Hey Hamza, can you please confirm you've done all of the following steps on this page: 

http://docs.ionic.io/setup.html

You'll need to make sure you have the cloud client installed and imported in your app.ts page.

**Comment by imhoffd** [comment]
@HamzaLJ If you're building an Ionic 2 app in JS (not TypeScript), you're undergoing a path that is not recommended by neither the Ionic team nor Angular team. You'll need to do more manual work, extra configuration, and code example translations like this one here. 

That code is a mix of ES6 and TypeScript (`const` is ES6, `CloudSettings` is a type for TypeScript). We don't have examples for ES5 (which is what you'd be using in an Angular 2 JS project following [this quickstart guide](https://angular.io/docs/js/latest/quickstart.html)), but I know at Ionic we're interesting in supporting this, but the need just hasn't been there yet. It's definitely possible today. Our distribution files include standard JS and a commonjs bundle.

In any case, the code translation to ES5 would be:

``` javascript
var cloudSettings = {
  'core': {
    'app_id': 'YOUR-APP-ID'
  }
};
```
