### ISSUE TITLE
Dev Push

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud-angular#2]
Digging trough the code It looks like dev_push has been removed,
https://github.com/driftyco/ionic-cloud/commit/8906ae31d1c604e0202eb12211737fcc25a786cf

I'm assuming I am seeing this because i am using the bleeding edge? am I correct? If this effects other users I would strongly recommend updating the docs.

I also have to mention I liked the dev_push feature. Although it does add some complication and is error prone, I think it fits nicely with Ionics philosophy of embracing the web.
It allows you to check your code/app while still in the browser which is I big plus despite the disadvantages.

 I think the problem was more to do with the terminology "limited_push", should have been something along the lines of "Browser Push"  and with the no need to switch a configuration (would have been better for the framework to decided by it's self if it's running in the browser.)

Happy to hear your thoughts :)

**Comment by imhoffd** [comment]
Moved :point_right: https://github.com/driftyco/ionic-cloud/issues/8
