### ISSUE TITLE
Using cloud in Ionic 2 Release candidate

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud-angular#20]
Hey guys!

I'm in the process of upgrading to ionic 2 release candidate and am struggling to figure out how to initialize it with cloudSettings.  Previously we did that in the AppComponent with `ionicBootstrap` and `provideCloud`.  But now that it seems everything is being done in the [app.module](https://github.com/driftyco/ionic2-starter-blank/blob/master/src/app/app.module.ts), I'm not sure how to get this working.  Would we still use provideCloud, and just put it in the `bootstrap` property?

Any advice would be much appreciated.  Thanks!

**Comment by imhoffd** [comment]
Hey @joshgarwood. [The docs](http://docs.ionic.io/setup.html#configuration) should be up-to-date with how to configure the cloud client and its providers.

We're aware of a current issue with ngc. See https://github.com/driftyco/ionic-cloud/issues/59

**Comment by joshgarwood** [comment]
D'oh!  I shoulda looked at the docs!  Sorry about that.  I'll keep my eye on the ngc issue.  Thanks!

**Comment by imhoffd** [comment]
@joshgarwood This should be all resolved. Let me know if you encounter any issues!
