### ISSUE TITLE
TypeScript error - Could not run ionic app including classes from cloud-angular

### ISSUE THREAD

**Issue by VladimirSpigiel** [driftyco/ionic-cloud-angular#24]
Hi there,

I'm trying to push notifications with an ionic2 app but I need to import classes from ionic-cloud-angular.
When I'm doing this, I have those errors : 

> TypeScript error: /home/crayer/dev/frontend/mobile/node_modules/@ionic/cloud/dist/es5/auth.d.ts(13,21): Error TS1110: Type expected.
> [ ... ]
> TypeScript error: /home/crayer/dev/frontend/mobile/node_modules/@ionic/cloud/node_modules/ionic-native/dist/es5/plugins/apprate.d.ts(46,21): Error TS1005: '=' expected.
> TypeScript error: /home/crayer/dev/frontend/mobile/node_modules/@ionic/cloud/node_modules/ionic-native/dist/es5/plugins/apprate.d.ts(46,32): Error TS1005: ';' expected.
> TypeScript error: /home/crayer/dev/frontend/mobile/node_modules/@ionic/cloud/node_modules/ionic-native/dist/es5/plugins/contacts.d.ts(39,14): Error TS1005: '=' expected.
> [...]

These are my information about ionic configuration : 
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04.1 LTS 
Node Version: v4.2.6

And here is my package.json : 

```
{
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@ionic/cloud-angular": "^0.5.2",
    "es6-shim": "0.35.1",
    "ionic-angular": "2.0.0-beta.11",
    "ionic-native": "1.3.10",
    "ionicons": "3.0.0",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
  "devDependencies": {

    "del": "2.2.0",
    "gulp": "3.9.1",
    "gulp-watch": "4.3.5",
    "ionic-gulp-browserify-typescript": "2.0.0",
    "ionic-gulp-fonts-copy": "^1.0.0",
    "ionic-gulp-html-copy": "^1.0.0",
    "ionic-gulp-sass-build": "^1.0.0",
    "ionic-gulp-scripts-copy": "^2.0.0",
    "ionic-gulp-tslint": "^1.0.0",
    "run-sequence": "1.1.5",
    "tslint-ionic-rules": "0.0.4"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [],
  "name": "mobile",
  "description": "mobile: An Ionic project"
}
```

I tried to install beta and stable version of ionic but there is nothing I can do to use the cloud classes ...

I hope someone could help

**Comment by imhoffd** [comment]
I think you're using new dependencies on an old app. The Ionic RC was released, and because of all the changes made, we can only really support it going forward (and not beta or alpha versions of Ionic 2). Check out the blog post: http://blog.ionic.io/announcing-the-ionic-2-release-candidate/ and the CHANGELOG: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc0-2016-09-28
