### ISSUE TITLE
ionic package build ios stuck in "Building" state

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud-angular#25]
Hi there!

I've tried several ionic package builds for ios since yesterday, and all of them are stuck in a "Building" state. I can build the app locally in both ios and android, and ionic package build android works like a charm. It's just ios that's not working.

Any word on what could be going on here? I know there were a few issues that got resolved earlier this week; thinking maybe this could be related?

Thanks for your time!

**Comment by imhoffd** [comment]
Builds appear to be going through as of a few seconds ago, can you try again? I know there were a few issues last week.

**Comment by joshgarwood** [comment]
Thanks for the quick response!  So I kicked off another ios build about 4.5 hours ago, and it's still in a "Building" state.  Is there any way I can get more visibility into what's going on.  Or is there a way I could replicate this on my local environment so I can debug?  ... At the moment building locally seems to work fine.

**Comment by imhoffd** [comment]
@joshgarwood Do you mind if we chat in the Ionic Worldwide slack?

**Comment by joshgarwood** [comment]
not at all... I'm on there now @noblyjosh

**Comment by dwieeb** [comment]
What's your username?

**Comment by joshgarwood** [comment]
Hey guys!  Sorry to be a pest, but this is still an issue for me; is there anything I can do to help diagnose?  We narrowed it down to the build stalling-out after trying to load a plugin from a remote git repository.  For the record, this works without an issue for Android; it's only iOS that's not building.

Thanks!

**Comment by ericb** [comment]
@joshgarwood What plugin? Is there any iOS 10 features involved?

**Comment by joshgarwood** [comment]
https://github.com/transistorsoft/cordova-background-geolocation-lt

I'm not sure if there are iOS 10 features; it does look like the developer recently made changes for new geofencing stuff, but other than that I don't know...

**Comment by imhoffd** [comment]
@joshgarwood Any reason you're using the git remote? npm is preferred (https://github.com/transistorsoft/cordova-background-geolocation-lt#installing-the-plugin)

Try `cordova plugin add cordova-background-geolocation-lt --save` and removing the git url from your app.

**Comment by joshgarwood** [comment]
well, this isnt the actual repo (i linked to it so yall could see the code).  THis is the "free" version.  The real repo is private, so we have to use a git remote like this:

`https://<username>:<password>@github.com/transistorsoft/cordova-background-geolocation.git`

**Comment by imhoffd** [comment]
Yeah, I figured that was the case. The problem is it's hard to debug this on our end without having access to the private repo.

**Comment by joshgarwood** [comment]
I believe the same thing happens with the public repo actually.  As
well, it works fine with Android.  If I can do anything else to help please
let me know.

**Comment by joshgarwood** [comment]
Sorry I meant public "repo" and that it works fine with "Android"

**Comment by joshgarwood** [comment]
Hey team!  Really sorry, but I'm still really struggling over here without an iOS build.  I can confirm that ionic package _does not work_ even when using the public repo: https://github.com/transistorsoft/cordova-background-geolocation-lt.git

That same repo works fine when doing ionic package for android.  When I try to get the `info` for the ios build I get the error below.  I am on rc1 using ionic-app-scripts version 36

```
$ ionic package info 75
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (C:\Users\josh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\package.js:116:27)
    at Request.self.callback (C:\Users\josh\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:373:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\josh\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\josh\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1266:12)
    at emitNone (events.js:91:20)
```

**Comment by imhoffd** [comment]
Very frustrating. I did `cordova plugin add --save https://github.com/transistorsoft/cordova-background-geolocation-lt.git` to my project and the build succeeds on iOS.  It also succeeds when I put it in `package.json`. I wonder what could be different between our apps.

**Comment by joshgarwood** [comment]
Did you build it through ionic package?  THat is the issue for us.  Building locally seems to work, but we need it to work through ionic package.

**Comment by imhoffd** [comment]
@joshgarwood and I resolved the issue! keychain issues with downloading a https github url with personal access tokens. We fixed up the problem on our servers and these should now function properly.

**Comment by papotte** [comment]
@dwieeb how did you resolve the problem? I have a similar problem at the moment and it might be a similar cause. I have created a Fork on one of the bower plugins. Could that be it?
