### ISSUE TITLE
Ionic resources failing during ionic package

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud-angular#28]
Hi there!

I recently updated my ionic-app-scripts to version 39, and when I tried to run `ionic package build android --profile dev` I got an error when the build tried to create my resources.  All of my resources files are in the appropriate folder(s) and this has worked in the past.  That said, the ionic package command seemed to finish executing without a problem.  The error I got is below:

```The resources folder already exists. We will not overwrite your files unless you pass the --force argument.
Running with the force flag will overwrite your resources directory and modify your config.xml file
Preparing your resources...
Caught exception:
 SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at C:\Users\josh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\io-config.js:169:24
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**Comment by imhoffd** [comment]
How weird. Do you happen to have an `.io-config.json` file in your project root?

**Comment by joshgarwood** [comment]
I do have an .io-config.json file in my root, but it's empty at the moment.  Should I remove it?

**Comment by imhoffd** [comment]
Yes, try removing it.

**Comment by joshgarwood** [comment]
Ok, i removed it and I did not get the ionic resources error.  However, the `io-config` file gets created again every time I run `ionic package` :/

**Comment by imhoffd** [comment]
@joshgarwood :/

Yeah, unfortunately we do need to keep that around for a while longer as to not break functionality with users of `ionic-platform-web-client` who have not fully migrated their apps yet.

Glad to hear the error has gone away!
