### ISSUE TITLE
User Password issues

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud-angular#3]
In order to use `user.resetPassword` you need to have a loaded user.
To have a loaded user you need to log him in which beats the purpose.

I thought `User.load('user-id’)` would do the trick, 
but -
1) This also beats the point as you don't have the user-id if your not logged in.
2) Tried hard coding it and `User.load('user-id’)` doesn't work, I get a 401 (missing token). (Perhaps this deserves it's own issue).

What am I missing? Is "reset password" different then "forgot password"?
If so what use case is it good for? Is there a plan to add "forgot password" functionality?

**Comment by imhoffd** [comment]
Moved 👉 https://github.com/driftyco/ionic-cloud/issues/9
