### ISSUE TITLE
Deploy cause protractor failure

### ISSUE THREAD

**Issue by itrethan** [driftyco/ionic-cloud-angular#31]
I am using protractor to test my app.

As long as there Deploy service is injected in the app during runtime, protractor would stop working.

**Comment by ericb** [comment]
Could you provide a little more context around what happens? My assumption is that the failure is caused due to the failure to load the Cordova plugin (something that will not work outside of a native device).

**Comment by imhoffd** [comment]
@itrethan Perhaps showing us the error message? Or even better, a simple ionic app repo outlining the problem?
