### ISSUE TITLE
ionic build ngc fails 

### ISSUE THREAD

**Issue by yasseralsamman** [driftyco/ionic-cloud-angular#33]
I'm facing this error when trying to build the app (**ionic build android**)

[15:23:18]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider  replacing the function or lambda with a reference to an exported function, 

resolving symbol CloudSettingsToken in /var/www/html/myApp/node_modules/@ionic/cloud-angular/dist/es5/index.d.ts, 

resolving symbol CloudModule in  /var/www/html/myApp/node_modules/@ionic/cloud-angular/dist/es5/index.d.ts

 resolving symbol  AppModule in /var/www/html/myApp/.tmp/app/app.module.ts,

 resolving symbol AppModule in  /var/www/html/myApp/.tmp/app/app.module.ts 

[15:23:18]  ngc failed 
[15:23:18]  ionic-app-script task: "build" 
[15:23:18]  Error: Error 

**My Package.json dependencies:**

    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/cloud-angular": "0.8.0",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.9",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "ts-md5": "^1.2.0",
    "zone.js": "~0.6.26"

    "@ionic/app-scripts": "0.0.46",
    "typescript": "2.0.6"

**cordova plugin list**

cordova-plugin-console 1.0.4 "Console"
cordova-plugin-device 1.1.3 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.0 "StatusBar"
cordova-plugin-whitelist 1.3.0 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**ionic info** 

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.1
Xcode version: Not installed

**UPDATE**
Reverting to "@ionic/cloud-angular": "0.7.0" seems to enable the ngc to finish.

**Comment by janpio** [comment]
Should probably be fixed with https://github.com/driftyco/ionic-cloud-angular/commit/c48298a2d316c7d0a841de3011993c5749991b10 Can you confirm @yasseralsamman ?
