### ISSUE TITLE
Error: Could not resolve '@ionic/cloud-angular'

### ISSUE THREAD

**Issue by bimal72** [driftyco/ionic-cloud-angular#34]
Hi,
To implement push notification, I installed Cloud Client, as per [https://docs.ionic.io/setup.html#installation](https://docs.ionic.io/setup.html#installation)

npm install @ionic/cloud-angular --save

Now in my app,here is code ..

```
import { CloudSettings, CloudModule } from '@ionic/cloud-angular';
.....
const cloudSettings: CloudSettings = {
  'core': {
    'app_id': 'MY_APP_ID'
  },
};
....
 imports: [
   
  CloudModule.forRoot(cloudSettings)
   
  ],
```

When I build in VSCode, it gives me following error..

11:39:34]  Error: Could not resolve '@ionic/cloud-angular' from F:\projects\ionic_project\.tmp\app\app.module.js

VSCode code intelligence works well, but while building from ionic CLI, it prompts the error

**Comment by sp3rk** [comment]
Have the same error with webstorm.

**Comment by gsavoie** [comment]
Also using webstorm here, everything seems to "compile" but when I do ionic serve it fails with the following

[19:08:46]  bundle dev failed:  Could not resolve '@ionic/cloud-angular' from C:\myProject\src\app\app.module.ts
[19:08:46]  Error: Could not resolve '@ionic/cloud-angular' from C:\myProject\src\app\app.module.ts
    at Error (native)
    at node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:78:21
    at C:\myProject\node_modules\browser-resolve\index.js:265:24
    at C:\myProject\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:14
    at process (C:\myProject\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\myProject\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\myProject\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\myProject\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\myProject\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)


This has been blocking me from using the cloud services :( could not find any workaround yet

**Comment by gsavoie** [comment]
I ended up upgrading @ionic/app-scripts to the latest version (currently 0.0.48), did the needed changes for the upgrade (see release notes) and now I dont get the error anymore.

Hope that helps anybody!

**Comment by rolandjitsu** [comment]
This is an actual issue with Rollup, @gsavoie by updating you just switched to Webpack which doesn't have this issue. But there is a [PR](https://github.com/driftyco/ionic-cloud-angular/pull/40) that will fix it.

**Comment by imhoffd** [comment]
@bimal72 @gsavoie @sp3rk Please try the latest 0.10.0 version. This should be fixed, thanks to @rolandjitsu !

**Comment by rolandjitsu** [comment]
I can confirm it's working, just tested it.

**Comment by DharmbirChoudhary** [comment]
try to install like this
**npm install @ionic/cloud-angular --save**
