### ISSUE TITLE
platform.toLowerCase is not a function

### ISSUE THREAD

**Issue by anatolesaby** [driftyco/ionic-cloud-angular#39]
Hello, 

I am having this error when I import Deploy from '@ionic/cloud-angular' and instanciate in my constructor. 
Like it is said in the documentation : http://docs.ionic.io/setup.html

Juste trying to lauch the application, no using the deploy.

For me, it worked good before I updated ionic, CLI and node_modules

An other guy @jsells on the Slack #technical-questions is facing the same issue 

<img width="320" alt="capture d ecran 2017-01-18 a 17 59 37" src="https://cloud.githubusercontent.com/assets/352598/22076824/0542ccaa-ddb2-11e6-9f16-314fb51d9665.png">

Thanks a lot

**Comment by selloutdesign** [comment]
you should print out your stack trace from console.

**Comment by nicobytes** [comment]
The same error, when I include **Auth** in constructor
![localhost-8100- iphone 5](https://cloud.githubusercontent.com/assets/7611944/22095509/5025da6a-dde3-11e6-91ad-21238dd66e63.png)

**Comment by anatolesaby** [comment]
For me the solution was to downgrade to "@ionic/cloud-angular": "^0.8.0"

**Comment by gligoran** [comment]
This seems to be a bug in `ionic-cloud`: https://github.com/driftyco/ionic-cloud/issues/140

**Comment by imhoffd** [comment]
0.9.1 or 0.10.0 should fix this. Thanks!
