### ISSUE TITLE
Build failure in iOS using ionic Packge

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud-angular#45]
Within the past several days I have noticed that I've been getting build failures using `ionic package build ios --profile [PROFILE_NAME]`, where PROFILE_NAME is `dev` or `prod` (I use --release if `prod` is specified).  In all cases, the build fails.  I was able to build successfully on March 4th, so this appears to be a recent issue.  Below is the very end of my build output for the `prod --release` command.  Please let me know if I can provide any further information:

```
Touch build/device/Nobly.app.dSYM
    cd /Users/package/workspace/apps-46d201fd-34/cordova/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/touch -c /Users/package/workspace/apps-46d201fd-34/cordova/platforms/ios/build/device/Nobly.app.dSYM

** ARCHIVE SUCCEEDED **

2017-03-06 20:22:05.405 xcodebuild[28326:2041214] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/kc/f8g8tr7n1054j1nzrkkvyzpr0000gq/T/Nobly_2017-03-06_20-22-05.405.xcdistributionlogs'.
2017-03-06 20:22:05.429 xcodebuild[28326:2041214] [MT] DeveloperPortal: Using pre-existing current store at URL (file:///Users/package/Library/Developer/Xcode/DeveloperPortal%207.3.1.db).
2017-03-06 20:22:05.854 xcodebuild[28326:2041214] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7ff3d8c46d80>: Error Domain=IDEDistributionErrorDomain Code=1 "(null)"
error: exportArchive: The operation couldn’t be completed. (IDEDistributionErrorDomain error 1.)

Error Domain=IDEDistributionErrorDomain Code=1 "(null)"

** EXPORT FAILED **

Error: Error code 70 for command: xcodebuild with args: -exportArchive,-archivePath,Nobly.xcarchive,-exportOptionsPlist,/Users/package/workspace/apps-46d201fd-34/cordova/platforms/ios/exportOptions.plist,-exportPath,/Users/package/workspace/apps-46d201fd-34/cordova/platforms/ios/build/device
```

Here is my output for `--profile dev ` (sensitive data is covered with *******)

```
Signing Identity:     "iPhone Developer: Josh Garwood (*******)"
Provisioning Profile: "nobly_development"
                      (*******)

    /usr/bin/codesign --force --sign ************** --entitlements /Users/package/Library/Developer/Xcode/DerivedData/Nobly-gtveufgzkaswqbembnttfwstvora/Build/Intermediates/ArchiveIntermediates/Nobly/IntermediateBuildFilesPath/Nobly.build/Debug-iphoneos/Nobly.build/Nobly.app.xcent --timestamp=none /Users/package/Library/Developer/Xcode/DerivedData/Nobly-gtveufgzkaswqbembnttfwstvora/Build/Intermediates/ArchiveIntermediates/Nobly/InstallationBuildProductsLocation/Applications/Nobly.app
**************: no identity found
Command /usr/bin/codesign failed with exit code 1

** ARCHIVE FAILED **


The following build commands failed:
	CodeSign /Users/package/Library/Developer/Xcode/DerivedData/Nobly-gtveufgzkaswqbembnttfwstvora/Build/Intermediates/ArchiveIntermediates/Nobly/InstallationBuildProductsLocation/Applications/Nobly.app
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/package/workspace/apps-46d201fd-36/cordova/platforms/ios/cordova/build-debug.xcconfig,-workspace,Nobly.xcworkspace,-scheme,Nobly,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,Nobly.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/package/workspace/apps-46d201fd-36/cordova/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/package/workspace/apps-46d201fd-36/cordova/platforms/ios/build/sharedpch
```

**Comment by joshgarwood** [comment]
Ok, I *may* have figured this out (sort of).  I added the ios platform version to my `cordovaPlatforms` recently in my package.json file.  This was to enforce that ios was build with the 64bit architecture... without it, the operating system throws this terrible message: ["This app may slow down you phone"](https://www.macrumors.com/2016/10/06/ios-10-1-32-bit-app-alert/).  

My cordovaPlatforms is below, but this is a rather major issue, because a message like that can discredit your app immediately.... However, if I remove this from my package.json the package build seems to work.

```
    "cordovaPlatforms": [
        {
            "platform": "ios",
            "version": "4.3.0",
            "locator": "ios"
        }
    ]
```

**Comment by joshgarwood** [comment]
@dwieeb is anyone from the ionic team monitoring these ionic cloud issues anymore?  Sorry to ping you directly, but getting this "This app will slow down your device" message is a huge deterrent for new users.  And my builds fail if i try to enforce using the 64bit build with the cordovaPlatform setting in my previous comment.  Any thoughts?

**Comment by imhoffd** [comment]
@joshgarwood A coworker and I are looking to upgrade Ionic Package to the latest Cordova/xcode/etc. There was a pretty big change that Apple introduced, but we've delayed the upgrade long enough. Package will be getting some love soon here.

**Comment by joshgarwood** [comment]
Hey @dwieeb !  Sorry to be a pest, but wanted to see if there's been any progress on this issue :)  Please use me as a tester; I'm happy to help at any time

**Comment by xx0r** [comment]
Is it possible that the upgrade is in progress? I'm getting errors packaging an app that went previously fine and I reckon it is related:

```
Check dependencies

Write auxiliary files
...
... : no identity found
Command /usr/bin/codesign failed with exit code 1

** BUILD FAILED **
```

**Comment by Slavrix** [comment]
So, Yesterday I was able to build on ios with no problems via ionic package
today I can't.

I rolled all my code back to see if it was an issue on my end and it still fails (ios only android works fine still)

Please advise.

```
Error Domain=IDEDistributionErrorDomain Code=1 "(null)"

** EXPORT FAILED **

Error: Error code 70 for command: xcodebuild with args: -exportArchive,-archivePath,Club Ezy.xcarchive,-exportOptionsPlist,/Users/package/workspace/apps-********-107/cordova/platforms/ios/exportOptions.plist,-exportPath,/Users/package/workspace/apps-********-107/cordova/platforms/ios/build/device
```

**Comment by berto-nts** [comment]
The same thing happens to me, fix please! 3 days ago worked!!

> ** EXPORT FAILED **
> 
> Error: Error code 70 for command: xcodebuild with args: -exportArchive,-archivePath,Plazatio.xcarchive,-exportOptionsPlist,/Users/package/workspace/apps-****-269/cordova/platforms/ios/exportOptions.plist,-exportPath,/Users/package/workspace/apps-****-269/cordova/platforms/ios/build/device

**Comment by vahidvdn** [comment]
@ordas Also I confronted with this issue today. More detail provided [here](https://forum.ionicframework.com/t/ionic-package-release-error-for-ios-building/90036).

**Comment by vahidvdn** [comment]
`ionic-app-scripts` is the way we go. I opened new issue [there](https://github.com/driftyco/ionic-app-scripts/issues/984).

**Comment by janpio** [comment]
> ionic-app-scripts is the way we go.

Uh why?

**Comment by vahidvdn** [comment]
@piotrowski As Ionic team suggest:

> Note: for build related issues you can open up an issue on the ionic-app-scripts repo

**Comment by janpio** [comment]
This is not related to the (local) build of your application, but an issue of the cloud build that Ionic Package. That is also why this here is also not really the correct place to post this, as there is no problem witn `ionic-cloud-angular` but the server that executes the cloud build. 

Use Zendesk to contact Ionic about issues with the cloud build of Ionic Package: https://ionic.zendesk.com/hc/en-us/requests/new?ticket_form_id=632068

**Comment by tlancina** [comment]
Hey all, we upgraded the default Cordova iOS version last night to 4.3.1 and it looks like it broke some release builds. I've moved the version back down to 4.2.0 for now while we investigate.

**Comment by berto-nts** [comment]
Thank you, it works!!!!

**Comment by berto-nts** [comment]
@tlancina, It does not work again, the same problem on Friday. We are crazy?

**Comment by tlancina** [comment]
Hey @ordas, we upgraded to Xcode 8.2.1 and Cordova iOS 4.3.1 as the default, so there may be some issues.  Can you submit a ticket to https://ionic.zendesk.com/hc/en-us/requests/new?ticket_form_id=632068 with your build log and we can troubleshoot there, thanks!

Just to clarify, the issue last week caused _all_ release builds to fail, which I can see is not the case right now, however there may be new problems that we'll need to address.

Going to close this as the original issue should be resolved.

**Comment by vahidvdn** [comment]
It seems everything works fine right now.

**Comment by vahidvdn** [comment]
@tlancina  Opps! Again, cannot build. Going to submit a ticket. Even native plugins does not work. For example can not open camera. (Doesn't ask for access in new devices)

**Comment by berto-nts** [comment]
Ok, @tlancina , I going to submit a ticket, but I think you should not close the issue because the error is the same:

> ** EXPORT FAILED **
> 
> Error: Error code 70 for command: xcodebuild with args: -exportArchive,-

**Comment by vahidvdn** [comment]
@ordas When the problem solved, please check whether your native plugins works or not. After @tlancina claimed that build works fine, It worked for one time, but my camera plugin didn't work. And now, build fails.

**Comment by berto-nts** [comment]
@vahidvdn Yes native plugins,  like cordova-plugin-camera or cordova-plugin-x-socialsharing works fine in development build.

**Comment by tlancina** [comment]
Just to reiterate, the previous issue was causing every single release build to fail.  This is no longer the case, and if there are individual issues please submit a ticket with information to help us track down the problem, thanks!

**Comment by berto-nts** [comment]
@tlancina I sent it! Ticket #1465

**Comment by vahidvdn** [comment]
@tlancina Sent. #1464

**Comment by vahidvdn** [comment]
@ordas Yes, cordova-plugin-x-socialsharing works fine, but camera doesn't!

**Comment by vahidvdn** [comment]
Now it works fine. After updating camera plugin to the latest version, it worked fine.

**Comment by renebesicke** [comment]
I had the same issue since friday but it still doesn't work for me. iOs still failes and gives me the error 70.
Can someone give me a hint? Do I have to put cordova platform iOS to 4.2.0 or isn't it necessary? (tryed it but didn't changed anything)

---

I'm on Ionic Version 2.2.2. Could that be a reason?

**Comment by berto-nts** [comment]
@rbesicke, My problem (error #70) was solved by updating the distribution certificate. My certificate had been revoked. Check that your certificate is correct

**Comment by vahidvdn** [comment]
@rbesicke 

> Do I have to put cordova platform iOS to 4.2.0

If you are using ionic cloud, I think it has nothing to do with your local cordova ios version or your local plugins. It builds your app by your config.xml file.

**Comment by renebesicke** [comment]
Thank you for your feedback! :)
I'll try it with updating our certificate. 
Which Ionic Version are you using?

**Comment by berto-nts** [comment]
@rbesicke 
 "ionic-native/core": "^3.2.3",

**Comment by renebesicke** [comment]
We recreated our certificate but it didnt helped. We saw now that it only fails when we create a production certificate. On a develope certificate it works fine.

**Comment by vahidvdn** [comment]
@tlancina It seems ionic package doesn't work. Status is always "building". No fail, no success. Any idea? (Ticket is sent)

**Comment by tlancina** [comment]
Hey there was an issue on the server this morning so builds got backed up,
the queue should clear soon.

**Comment by vahidvdn** [comment]
@tlancina Hey. Is there any issue today with ionic package?

**Comment by ProMasoud** [comment]
@tlancina  same problem :( , Any idea?

**Comment by vahidvdn** [comment]
Now, works fine.

**Comment by cagb80** [comment]
Use the new cordova iOs version:
cordova platform add ios@4.5.1

This work for me!

**Comment by gp187** [comment]
@cagb80 can you share the config? Still doesn't work for me. 
I'm trying to put it on CircleCI and not working at all! 
Same error as above no matter what version I use

What version XCode you use?

**Comment by cagb80** [comment]
Hi @gp187 I'm on xCode 9.0 I found another solution for this bug. Check this:

1. You have to create the App Id in the Apple Developer Platform.
2. You have to download in xCode the Provisioning Profiles that you created on Apple Developer Platform.
3. Here the magic:
a. Remove iOs platform. `ionic platform rm ios`
b. Add iOs platform but do not build it yet...!!! `ionic platform add ios`
c. Open the iOs project in xCode.
Select your Developer Team account and check Automatic Profile... (Just for development)
d. Go back to the Terminal to build your iOs platform - `ionic build iOs`

Try it... I test it... I using to Develop this way.
When you going to build the production iOs platform. You have to select the correct Profile.

Let's me know if this work for you.

**Comment by gp187** [comment]
Manually it works, that wasn't the problem. 
What doesn't work is for my CI using CircleCI. Any idea how that can be done only with command line tools ?

**Comment by cagb80** [comment]
Sorry @gp187 I don't use CircleCI. Let's me read something about.

**Comment by gp187** [comment]
Basically how do you do the xcodebuild config without ever opening the XCODE on your desktop. 
CircleCI handles the profile and certificate quite nicely all you have to do is build. 

I tried everything but ionic still doesn't build 
```
ionic cordova build ios --release --buildConfig=build.json
```

```json
{
  "ios": {
    "debug": {
      "developmentTeam": "SSSTEAM",
      "codeSignIdentity": "Name of certficated",
      "provisioningProfile": "xxx-xxxx-xxxx-xxxx",
      "buildFlag": [
        "EMBEDDED_CONTENT_CONTAINS_SWIFT=YES",
        "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
        "CODE_SIGN_IDENTITY=Name of certficated",
        "DEVELOPMENT_TEAM=SSSTEAM",
        "CODE_SIGN_STYLE=Manual",
        "PROVISIONING_PROFILE=xxx-xxxx-xxxx-xxxx"
      ]
    }
  }
}

```

This is what I'm trying. 
Using the mobile provision and certificate works fine on desktop .
Any ideas @cagb80 ?
