### ISSUE TITLE
Doesnt work with Angular 4.0.0-rc.2 aot build

### ISSUE THREAD

**Issue by alexthebuilder** [driftyco/ionic-cloud-angular#46]
When running ionic build --prod using Angular 4.0.0-rc.2 the below error is thrown. ionic serve runs with no errors.

[15:12:06]  Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function 
            calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
            resolving symbol Injectable in 
            /node_modules/@ionic/cloud-angular/node_modules/@angular/core/src/di/metadata.d.ts,
            resolving symbol OpaqueToken in 
            /node_modules/@ionic/cloud-angular/node_modules/@angular/core/src/di/opaque_token.d.ts,
            resolving symbol OpaqueToken in 
            /node_modules/@ionic/cloud-angular/node_modules/@angular/core/src/di/opaque_token.d.ts
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /node_modules/@ionic/cloud-angular/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /node_modules/@ionic/cloud-angular/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /node_modules/@ionic/cloud-angular/node_modules/@angular/core/src/di/opaque_token.d.ts
    at Error (native)
    at syntaxError (/node_modules/@angular/compiler/bundles/compiler.umd.js:1273:19)
    at simplifyInContext (/node_modules/@angular/compiler/bundles/compiler.umd.js:16434:25)
    at StaticReflector.simplify (/node_modules/@angular/compiler/bundles/compiler.umd.js:16446:15)
    at StaticReflector.annotations (/node_modules/@angular/compiler/bundles/compiler.umd.js:15978:45)
    at NgModuleResolver.resolve (/node_modules/@angular/compiler/bundles/compiler.umd.js:9521:67)
    at CompileMetadataResolver.getNgModuleMetadata (/node_modules/@angular/compiler/bundles/compiler.umd.js:9951:45)
    at addNgModule (/node_modules/@angular/compiler/bundles/compiler.umd.js:15825:43)
    at /node_modules/@angular/compiler/bundles/compiler.umd.js:15836:16
    at Array.forEach (native)

**Comment by alexthebuilder** [comment]
Hopefully this can get some attention now that angular 4 is released.

**Comment by danitt** [comment]
+1

**Comment by danitt** [comment]
if it helps, @alexthebuilder , downgrading cloud-angular to 0.7.0 quashes the error (it's a dirty fix, but seems to work in the interim)

referenced in #33

**Comment by vitorlopez** [comment]
+1

**Comment by ihadeed** [comment]
Just encountered the same issue.

It's because `@angular/core` is defined in `package.json` under `dependencies` instead of `peerDependencies`.

What I did to fix it is delete `node_modules/@ionic/cloud-angular/node_modules` directory.

**Comment by youssmak** [comment]
up.
doesn't work with ionic 3.

**Comment by tobiasmuecksch** [comment]
I got the same issue! @ihadeed 's workaround didn't work for me :-(

**Comment by tonirilix** [comment]
As @danitt said, I quick fix that helped me as well was to downgrade @ionic/cloud-angular to 0.7.0. 

It will depend on what library is throwing the error but for the last version this was the only one with the problem.

**Comment by Ross-Rawlins** [comment]
this is still an issue.

**Comment by billykong** [comment]
I did `rm -r node_modules/@ionic/cloud-angular/node_modules` to solve the issue.
