### ISSUE TITLE
I think ionic 2 is a nightmare, don't use it

### ISSUE THREAD

**Issue by ghost** [driftyco/ionic-cloud-angular#51]
I think ionic 2 is a nightmare, don't use it

**Comment by ivanmayes** [comment]
Very Insightful, thanks for sharing.

**Comment by ghost** [comment]
ion-content scrolling mechanism is heavily lagging, i have to re-implement the whole slider, as there are loading issues, and index issues (showing some sort of virtual slider in a loop with empty content). I have wasted 3 weeks to hack the styles to make it correct in the ionic content, initially i had a project only using angular 4 (ionic angular 3.0.1 requires angular 4, but the thing is, the basic ionic card just collapsed, not stretched on the screen). As there is lots of bugs in ionic 2 and i need to google the debugger every time, i think it's just lost the point to use it. At the moment the calendar slider is the only valid point, what i don't want to re-implement, but i slightly moving away from it. I'm not satisfied also about angular as a whole, as it took me more time to implement certain component, and it is slower than the original one. Maybe the code is testable but i'm not sure about maintainability at the moment.

I'm not complaining, but re-implementing the basic components to me seems less time than use the ionic.

**Comment by ivanmayes** [comment]
Hey @raxim1, I'm not with Ionic, but if you have any specific grievances with Ionic, you should post issues about them in https://github.com/driftyco/ionic which is the repo for the ionic app.  This repo is for the cloud services like Deploy and Push.

**Comment by mhartington** [comment]
Hey there! If you're running into issues, please feel free to ask on the [Ionic forum](https://forum.ionicframework.com). As this is a repo for the ionic cloud library, it's not really the best place to post about framework related issues. 

I will also note that Ionic has a [Code of Conduct](https://github.com/driftyco/ionic/blob/master/CODE_OF_CONDUCT.md). If you would like to report issues on the framework, please do so in a professional manner or disciplinary actions will need to be taken.
