### ISSUE TITLE
0.0.13/0.0.14 build seem broken

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud-angular#6]
Got typescript Errors when updated.

Might have to do with the `ionic-cloud` version dependency not being updated to ' 0.8.0-beta.11', but I wasn't able to make that work.

![image](https://cloud.githubusercontent.com/assets/1857466/16538885/e3f47064-4039-11e6-82b3-86010d4e457b.png)

![image](https://cloud.githubusercontent.com/assets/1857466/16538929/09a6c25c-403b-11e6-8a19-4741283eae88.png)

Tried to debug it, but oddly the `src folder` in the npm_modules folder looks very different then the src folder in github https://github.com/driftyco/ionic-cloud/blob/master/src/index.ts.

**Comment by imhoffd** [comment]
Try 0.0.14. I just forgot to bump the version of `ionic-cloud`.

**Comment by sagivf** [comment]
Thanks  @dwieeb , but now I'm getting this - 
![image](https://cloud.githubusercontent.com/assets/1857466/16542277/25ed6f86-40ab-11e6-9f55-5f77ed083c6b.png)

Looks like the es5 dist folder is missing the auth module
![image](https://cloud.githubusercontent.com/assets/1857466/16542283/427688ae-40ab-11e6-8156-a96d7c8a5dfd.png)

I have no Idea how the Typesciprt stuff gets bundled in the node_modeuls so I can'y really debug what's going on....

**Comment by imhoffd** [comment]
What version is specified in your `package.json` for `@ionic/cloud-angular`? I was getting the exact same errors until I changed it to `*` and reinstalled.

**Comment by sagivf** [comment]
It was 0.0.14, tried *, still doesn't work.
Can you explain something:

I see Auth is exported twice, once here, 
https://github.com/driftyco/ionic-cloud-angular/blob/master/src/index.ts#L1 (`export * from '@ionic/cloud';`)
And once here - https://github.com/driftyco/ionic-cloud-angular/blob/master/src/index.ts#L5

The second time it is used to add an @Injectable .
Does typesciprt always use the second one?
Why is the @Injectable here is never inject it myself?

**Comment by sagivf** [comment]
I Ask this because - https://github.com/driftyco/ionic-cloud-angular/commit/540400b6fcd2667fbc1992e2c4bc35e6376cdba7 is pretty recent which makes me suspect it's the colporate.

**Comment by cklanac** [comment]
I'm also having issues with the upgrade. A rudimentary Auth.signup and Auth.login, which worked with 0.0.12, no longer works on 0.0.14. The signup and login methods we static in 0.0.12 but now seem to be instance methods.

Was:
`static login(moduleId, options: LoginOptions = {}, data): Promise<User> {`
Now:
`login(moduleId: AuthModuleId, data?: Object, options: LoginOptions = {'remember': true}): Promise<IUser> {`

I did a clean install `ionic start ionicv2-platform-auth sidemenu --v2 --ts`
Added cloud-angular `npm install --save @ionic/cloud-angular`
Initialized the app `ionic io init`
And wired it up...

The TS error is...
`Property signup does not exists on 'type of Auth'`

```
import { Component, ViewChild } from '@angular/core';
import { App, ionicBootstrap, Platform, Nav } from 'ionic-angular';
import { Auth, User, CloudSettings, provideCloud } from '@ionic/cloud-angular';
import { StatusBar } from 'ionic-native';
import { Page1 } from './pages/page1/page1';
import { Page2 } from './pages/page2/page2';

const cloudSettings: CloudSettings = {
  'core': {
    'app_id': "1f589081"
  }
};

@Component({
  templateUrl: 'build/app.html'
})
class MyApp {
  @ViewChild(Nav) nav: Nav;
  rootPage: any = Page1;
  pages: Array<{ title: string, component: any }>

  constructor(private platform: Platform) {
    this.initializeApp();

    // used for an example of ngFor and navigation
    this.pages = [
      { title: 'Page uno', component: Page1 },
      { title: 'Page dos', component: Page2 }
    ];
  }

  ngOnInit() {
    console.log('app ngOnInit');
    var details = {
      'email': 'example@example.com',
      'password': 'secretpassword'
    };
    /**** The following approach worked in 0.0.12 *****/
    Auth.signup(details).then(() => {
      console.log("`user` is now registered");
    }, (err) => {
      console.log("something went wrong!")
    });
  }

  initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });
  }

  openPage(page) {
    // Reset the content nav to have just this page
    // we wouldn't want the back button to show in this scenario
    this.nav.setRoot(page.component);
  }
}

ionicBootstrap(MyApp, [provideCloud(cloudSettings)]);
```

**Comment by sagivf** [comment]
@dwieeb I think this needs re opening...

**Comment by imhoffd** [comment]
@cklanac The Auth service no longer has those static methods. 0.0.14 was a big change. Try this:

``` typescript
import {Component} from '@angular/core';
import {Auth, User} from '@ionic/cloud-angular';

@Component( ... )
export class MyApp {
  constructor(public auth: Auth, public user: User) {
    ...
  }

  ngOnInit() {
    console.log('app ngOnInit');
    var details = {
      'email': 'example@example.com',
      'password': 'secretpassword'
    };

    this.auth.signup(details).then(() => {
      // success
    }, (err) => {
      console.log("something went wrong!")
    });
  }
}
```

The login method data and options parameters were swapped, because options should come after required parameters. 

Try something like:

``` typescript
this.auth.login('basic', {'email': 'example@example.com', 'password': 'secretpassword'});
```

**Comment by imhoffd** [comment]
@sagivf The typescript errors are correct. It's saying you can't call `login`/`logout`/etc on `Auth` class because they're no longer static methods. 0.0.14 had some changes from 0.0.12. See above. They're quick changes. Just inject the service into your constructor(s) and instead of `Auth` use `this.auth`.

Similarly, always use the `this.user` variable to reference the current user.

This library and the `ionic-cloud` client aren't full releases. We're still very much in beta and we're still trying to develop the best API for the client, which is why we've opened discussions such as https://github.com/driftyco/ionic-cloud-angular/issues/1,  https://github.com/driftyco/ionic-cloud/issues/3, and https://github.com/driftyco/ionic-cloud/issues/13.

**Comment by sagivf** [comment]
I think I tried it and it failed but I will try again soon.

**Comment by sagivf** [comment]
Hey @dwieeb, so you are correct changing it to instances work nicely 👍 
There are a couple of related  issues/comments:
https://github.com/driftyco/ionic-cloud/issues/10#issuecomment-230178315
https://github.com/driftyco/ionic-cloud-angular/issues/7

**Comment by imhoffd** [comment]
Nice, glad to hear! :+1:
