### ISSUE TITLE
unable to install plugin in new ionic 3 project

### ISSUE THREAD

**Issue by vksgautam1** [driftyco/ionic-cloud-angular#60]
this is the error.
[code]
>npm i @ionic/cloud-angular
ionic-hello-world@0.0.0 E:\crown_sales
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'E:\crown_sales\node_modules\ionic-native\package.json'
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@ionic/cloud-angular"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path E:\crown_sales\node_modules\.staging\rxjs-d38609b6
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'E:\crown_sales\node_modules\.staging\rxjs-d38609b6' -> 'E:\crown_sales\node_modules\@ionic\cloud\node_modules\rxjs'
npm ERR!  { Error
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'E:\crown_sales\node_modules\.staging\rxjs-d38609b6' -> 'E:\crown_sales\node_modules\@ionic\cloud\node_modules\rxjs' parent: '@ionic/cloud' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2017-06-15T07_53_43_754Z-debug.log
[/code]

 ordova CLI: 6.5.0
Ionic Framework Version: 3.3.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.10.0
Xcode version: Not installed

**Comment by vksgautam1** [comment]
i made another project . it got installed in that.

**Comment by PremkumarAgrawal** [comment]
Hii all,

I am facing this issue while installing IONIC on my PC win10, do you have any idea what should I do...

`D:\A_KY_Projects\K3_MART\K3_MART_APP_CODE\K3_Mart>npm install -g ionic
C:\Users\PREM\AppData\Roaming\npm\ionic -> C:\Users\PREM\AppData\Roaming\npm\node_modules\ionic\bin\ionic
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\ionic\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ionic@3.12.0
added 350 packages in 120.577s`

**Comment by imhoffd** [comment]
@PremkumarAgrawal That's just a warning. There's no issue.
