### ISSUE TITLE
0.0.14 Push issues

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud-angular#7]
1) Know that we are injecting the push instance, how do we send PushOptions to the constructor?

```
constructor(deps: PushDependencies, options?: PushOptions);
```

2) I'm getting console errors in the browser I wasn't getting before:
![image](https://cloud.githubusercontent.com/assets/1857466/16547876/2de737b0-4184-11e6-8976-ad199f343d98.png)

3) Push no longer has an onReady function, is it not needed?

Here's the code i'm using:

``` javascipt
  this.platform.ready().then(() => {
      //this.push.onReady(() => {
        this.push.register().then((token) => {
          console.log("Device token:", token.token);
          this.push.saveToken(token);
        });
      //});
    });
```

**Comment by imhoffd** [comment]
1. Push options are part of the config now. But, there aren't many options. If you're looking for where to put your `onNotification` handler, it's done through the event emitter (for now... later it may be an observable). 
   
   ``` typescript
   const cloudSettings: CloudSettings = {
     'core': {
       'app_id': "YOUR-APP-ID"
     },
     'push': {} // PushOptions
   };
   ```
   
   ``` typescript
   import {EventEmitter} from '@ionic/cloud-angular';
   ```
   
   ``` typescript
   constructor(emitter: EventEmitter)
   ```
   
   ``` typescript
   emitter.on('push:notification': (data) => { });
   ```
2. The `onReady` function/callback is not needed, correct.
3. The console errors in the plugin are also correct -- you cannot do native push notifications in the browser. They are "uncaught" promise errors, but they are still ugly. Maybe I can clean them up somehow.

**Comment by sagivf** [comment]
Thanks for the detailed response @dwieeb, much appreciated. 
It works nicely :)
Regarding number 3, till proper mocking or better yet an ionic-browser push implementation is created catching the errors our selves is ok.
Generally speaking I think that all the ionic-native cordova plugins should come with a browser mock.\

I believe that Ionic's long time strength in my view is enabling web developers to use the tools they know and love.

**Comment by imhoffd** [comment]
I agree. We're very interested in implementing browser pushes & deploy functionality for the browser. The browser is a proper platform for Ionic and I think it will do us well to treat it as one for Ionic Cloud.

It sounds like these issues are resolved. If they are not, no worries. I'll reopen.

**Comment by sagivf** [comment]
Thanks @dwieeb, not related to this issue, but Ionic and Ionic Platform have given me a lot of headaches over the past two years :) (to be fare a lot of the headache is Apple/Cordova related), but the dedication and responsiveness from you guys has kept me going and I do believe things are on the right track - keep it up and thanks for the hard work 👍

**Comment by imhoffd** [comment]
@sagivf Haha, yep. Ionic is venturing into uncharted territories and bringing a bunch of people with! I also think things are on the right track and I believe it's because of people like you. Thanks so much for working with me. This is the feedback we've needed. 🍻
