### ISSUE TITLE
Update to Angular RC.4

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic-cloud-angular#9]
Please update the peer dependency in `package.json` so we can use this with Ionic beta 11 :)

It should be compatible already, I think.

**Comment by imhoffd** [comment]
@Manduro I'm thinking we loosen up the requirement a bit. I don't need to specify an exact version of Angular (at least until they release the provider changes).

**Comment by Manduro** [comment]
Sure, even better. The fixed dependency already surprised me a bit.

**Comment by SteveKennedy** [comment]
Scratch that.  Make it RC.5.

**Comment by imhoffd** [comment]
@Manduro @SteveKennedy We're waiting on the release of Ionic beta.12.

rc.5 has changed the [way bootstrapping works](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html#!#2-create-an-_ngmodule_) in a way that `ionicBootstrap()` needs to be reworked. We won't be using providers as we are right now, so the next version of `ionic-cloud-angular` will require rc.5 and use NgModules.

**Comment by Manduro** [comment]
Cool! Meanwhile I'm using my fork successfully with rc.4.

**Comment by joshgarwood** [comment]
@dwieeb sorry to be a bother, but do you know if there is going to be a fix for this before beta 12?

Thanks!

**Comment by imhoffd** [comment]
@joshgarwood I'm working on releasing a version in the next couple hours here to fix this warning. When beta 12 is released and you update your apps, you'll need to install the new rc.5 version of Angular. At that point, you'll need to also update the cloud client as to not be using deprecated code.

**Comment by joshgarwood** [comment]
Ok rock on, that sounds great.  Thanks so much!!

**Comment by imhoffd** [comment]
@joshgarwood @Manduro @SteveKennedy We now have a version range specified for angular so that warning should go away unless you're using rc.5. If you're using rc.5, the warning should _actually_ be there.

Update your `@ionic/cloud-angular`!

https://github.com/driftyco/ionic-cloud-angular/blob/master/package.json#L43-L44
